### ISSUE TITLE
Field [_id] is defined twice

### ISSUE THREAD

**Issue by bompi88** [Alino/Mongo2ES#9]
Getting duplicate `_id` error when using Elasticsearch 2.2. Maybe I'm doing something wrong? My transform method looks as follows,

``` js
var transform = function (doc) {
  doc._id = doc._id._str ? doc._id._str : doc._id;
  return doc;
};
```

The error I'm getting is below,

```
{
   [
      Error:failed      [
         400
      ]      {
         "error":{
            "root_cause":[
               {
                  "type":"remote_transport_exception",
                  "reason":"[Hamilton Slade][172.17.0.3:9300][indices:data/write/index[p]]"
               }
            ],
            "type":"illegal_argument_exception",
            "reason":"Field [_id] is defined twice in [docs]"
         },
         "status":400
      }
   ]   stack:[
      Getter
   ]
}
```

What I did to solve the problem was instead of 

``` js
query = newDocument
```

I did

``` js
query = _.omit(newDocument, '_id')
```

**Comment by Alino** [comment]
@bompi88 sorry for the delay, I was kind of busy with my startup.
Thank you for your commitment I appreciate that.

I was using ElasticSearch 1.7.x where it works fine, so I didn't notice this.
But [latest Mongo2ES CI tests with ElasticSearch 2.x are failing due to this error](https://circleci.com/gh/Alino/Mongo2ES/29).
We need to omit the _id in the document, your pull requests fixes the problem, merged into dev branch for now. I will later merge it into master.

**Comment by bompi88** [comment]
@Alino NP :wink:

**Comment by Alino** [comment]
merged :)
